[versions]
#   Activity Compose
activity-compose = "1.7.2"

#   AGP Version
agp = "8.1.0-beta02"

#   Kotlin Android
org-jetbrains-kotlin-android = "1.8.10"

#   KTX
core-ktx = "1.10.1"

#   Compose BOM
compose-bom = "2023.06.00"

#   Coil
coil-version = "2.4.0"

#   Espresso
espresso-core = "3.5.1"

#   Hilt
hilt-version = "2.46.1"
hilt-compose-version = "1.0.0"

#   JUnit & Android JUnit
androidx-junit-version = "1.1.5"
junit-version = "4.13.2"

#   KSP
ksp-version = "1.0.9"

#   Logging Interceptor
logging-version = "4.11.0"

#   Moshi
moshi-version = "1.14.0"

#   ViewModel
viewmodel-version = "2.6.1"

#   Retrofit
retrofit-version = "2.9.0"

[libraries]

#   Coil
coil = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil-version" }

#   Compose
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
ui = { group = "androidx.compose.ui", name = "ui" }
ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }

#   Espresso
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }

#   Hilt
hilt = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt-version" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt-version" }
hilt-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hilt-compose-version" }
hilt-work = { group = "androidx.hilt", name = "hilt-work", version.ref = "hilt-version" }
hilt-work-compiler = { group = "androidx.hilt", name = "hilt-compiler", version.ref = "hilt-version" }

#   Junit & Android JUnit
junit = { group = "junit", name = "junit", version.ref = "junit-version" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-junit-version" }

#   KTX
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }

#   Logging Interceptor
logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "logging-version" }

#   Material
material3 = { group = "androidx.compose.material3", name = "material3" }

#   Moshi
moshi = { group = "com.squareup.moshi", name = "moshi", version.ref = "moshi-version" }

#   Retrofit
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit-version" }

#   Viewmodel
viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "viewmodel-version" }
viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "viewmodel-version" }



[plugins]

#   Android Application
com-android-application = { id = "com.android.application", version.ref = "agp" }

#   Android Module
com-android-library = { id = "com.android.library", version.ref = "agp" }

#   Kotlin Android
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "org-jetbrains-kotlin-android" }

#   KSP
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp-version" }

#   Moshi-Codegen
moshi-codegen = { id = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi-version" }

[bundles]

